### ISSUE TITLE
9.1.0-Plus TSBattery 模块闪退问题

### ISSUE THREAD

**Issue by xqltt** [Nekozuka-Hibiki/QQ-SyRadiant#10]
启动一段时间后在设置中点击TSBattery会闪退,此现象在前几个版本就已经有出现,此版本较为严重(9.0.65版本无此现象)

**Comment by Nekozuka-Hibiki** [comment]
啊，兄弟莫不是在为难我。
为什么会启动一段时间后启动TSB闪退？这个模块的作用不是阻断core进程吗，应该是一次设置就不用再进去界面的吧？
闪退的原因应该不是sy，TSB启动后会联网，联网失败会闪退。

**Comment by xqltt** [comment]
测试了一下,闪退后的首次进入是正常能打开TSB的设置界面的,过一段时间(比如看频道之类的)在回来点TSB会有这个问题,长时间不点击TSB后台仍然高耗电(低版本之前没这个问题)

**Comment by Nekozuka-Hibiki** [comment]
可能是模块不适配吧大概？或者是我的问题，不过TSB模块本身不是很重要的功能，能使就行。

**Comment by xqltt** [comment]
也有可能是高版本QQ改了一些逻辑,影响到TSB模块自动适配的运行,目前想阻止后台高耗电只能用旧版本的了
