### ISSUE TITLE
qq循环闪退，清除后台无法解决问题

### ISSUE THREAD

**Issue by aizaimosaou** [Nekozuka-Hibiki/QQ-SyRadiant#11]
你好，我的机型是魅族17pro，最新flyme10系统。qq是plus版本。安装qq后会出现闪退情况。一般打开2秒到3秒后会闪退。强行关闭或者后台均不行

我能否以抓取错误日志，反馈于你的形式。来共同解决这个问题。8.x的老版本我是一直正常使用的。

**Comment by Nekozuka-Hibiki** [comment]
你会抓错误日志的话可以发一份看看

**Comment by Tartuffe-X** [comment]
> 你会抓错误日志的话可以发一份看看

目前我遇到的循环闪退日志如下

FATAL EXCEPTION: main
Process: com.tencent.mobileqq, PID: 24806
java.lang.RuntimeException: Unable to instantiate application com.tencent.common.app.QFixApplicationImpl package com.tencent.mobileqq: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1511)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1439)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7213)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1251)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503)
	... 11 more

**Comment by aizaimosaou** [comment]
你好，这是附件，依次打开了两次app，在最后一次打开qq的时候，出现了闪退情况







在 2024-09-26 06:50:55，"Tartuffe-X" ***@***.***> 写道：

你会抓错误日志的话可以发一份看看

目前我遇到的循环闪退日志如下

FATAL EXCEPTION: main
Process: com.tencent.mobileqq, PID: 24806
java.lang.RuntimeException: Unable to instantiate application com.tencent.common.app.QFixApplicationImpl package com.tencent.mobileqq: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1511)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1439)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7213)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8423)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
at android.app.Instrumentation.newApplication(Instrumentation.java:1251)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503)
... 11 more

**Comment by Nekozuka-Hibiki** [comment]
> 你好，这是附件，依次打开了两次app，在最后一次打开qq的时候，出现了闪退情况 在 2024-09-26 06:50:55，"Tartuffe-X" ***@***.***> 写道： 你会抓错误日志的话可以发一份看看 目前我遇到的循环闪退日志如下 FATAL EXCEPTION: main Process: com.tencent.mobileqq, PID: 24806 java.lang.RuntimeException: Unable to instantiate application com.tencent.common.app.QFixApplicationImpl package com.tencent.mobileqq: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1511) at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1439) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7213) at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:240) at android.os.Looper.loop(Looper.java:351) at android.app.ActivityThread.main(ActivityThread.java:8423) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259) at java.lang.ClassLoader.loadClass(ClassLoader.java:637) at java.lang.ClassLoader.loadClass(ClassLoader.java:573) at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) at android.app.Instrumentation.newApplication(Instrumentation.java:1251) at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503) ... 11 more — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
> 你好，这是附件，依次打开了两次 app，在最后一次打开 qq 的时候，出现了闪退情况。 翻译文本：你好，这是附件，我依次打开了两次 app，在最后一次尝试打开 qq 时，出现了程序崩溃的情况 在 2024-09-26 06:50:55，“Tartuffe-X” ***@***.***> 写道： Translation Text: 你会抓错误日志的话可以发一份看看 目前我遇到的循环闪退日志如下 致命异常：主 进程: com.tencent.mobileqq, PID: 24806 java.lang.RuntimeException: 无法实例化应用 com.tencent.common.app.QFixApplicationImpl 包 com.tencent.mobileqq：找不到类 "com.tencent.common.app.QFixApplicationImpl"，路径：DexPathList[[zip 文件 "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],本地库目录=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] 在 android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1511) 在 android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1439) 在 android.app.ActivityThread.handleBindApplication(ActivityThread.java:7213) 在 android.app.ActivityThread.-$$Nest$mhandleBindApplication（未知源：0） 在 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292) 在 android.os.Handler.dispatchMessage(Handler.java:106) 在 android.os.Looper.loopOnce(Looper.java:240) 在 android.os.Looper.loop(Looper.java:351) 在 android.app.ActivityThread.main(ActivityThread.java:8423) 在 java.lang.reflect.Method.invoke（Native Method） 在 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 在 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) 原因：找不到类 "com.tencent.common.app.QFixApplicationImpl"，在路径：DexPathList[[zip 文件 "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] 在 dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259) 在 java.lang.ClassLoader.loadClass(ClassLoader.java:637) 在 java.lang.ClassLoader.loadClass(ClassLoader.java:573) 在 android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) 在 android.app.Instrumentation.newApplication(Instrumentation.java:1251) 在 android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503) 创建应用内部 ... 11 个更多 — 直接回复这封电子邮件，查看 GitHub 上的内容，或取消订阅。 您收到此消息是因为您是该主题的作者。消息 ID：***@***.***

我看不到附件？

**Comment by aizaimosaou** [comment]
你好，我再尝试发送一下










在 2024-09-28 23:37:11，"Nekozuka-Hibiki" ***@***.***> 写道：

你好，这是附件，依次打开了两次app，在最后一次打开qq的时候，出现了闪退情况 在 2024-09-26 06:50:55，"Tartuffe-X" @.> 写道： 你会抓错误日志的话可以发一份看看 目前我遇到的循环闪退日志如下 FATAL EXCEPTION: main Process: com.tencent.mobileqq, PID: 24806 java.lang.RuntimeException: Unable to instantiate application com.tencent.common.app.QFixApplicationImpl package com.tencent.mobileqq: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1511) at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1439) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7213) at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:240) at android.os.Looper.loop(Looper.java:351) at android.app.ActivityThread.main(ActivityThread.java:8423) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.common.app.QFixApplicationImpl" on path: DexPathList[[zip file "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259) at java.lang.ClassLoader.loadClass(ClassLoader.java:637) at java.lang.ClassLoader.loadClass(ClassLoader.java:573) at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) at android.app.Instrumentation.newApplication(Instrumentation.java:1251) at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503) ... 11 more — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>
你好，这是附件，依次打开了两次 app，在最后一次打开 qq 的时候，出现了闪退情况。 翻译文本：你好，这是附件，我依次打开了两次 app，在最后一次尝试打开 qq 时，出现了程序崩溃的情况 在 2024-09-26 06:50:55，“Tartuffe-X” @.> 写道： Translation Text: 你会抓错误日志的话可以发一份看看 目前我遇到的循环闪退日志如下 致命异常：主 进程: com.tencent.mobileqq, PID: 24806 java.lang.RuntimeException: 无法实例化应用 com.tencent.common.app.QFixApplicationImpl 包 com.tencent.mobileqq：找不到类 "com.tencent.common.app.QFixApplicationImpl"，路径：DexPathList[[zip 文件 "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],本地库目录=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] 在 android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1511) 在 android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1439) 在 android.app.ActivityThread.handleBindApplication(ActivityThread.java:7213) 在 android.app.ActivityThread.-$$Nest$mhandleBindApplication（未知源：0） 在 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292) 在 android.os.Handler.dispatchMessage(Handler.java:106) 在 android.os.Looper.loopOnce(Looper.java:240) 在 android.os.Looper.loop(Looper.java:351) 在 android.app.ActivityThread.main(ActivityThread.java:8423) 在 java.lang.reflect.Method.invoke（Native Method） 在 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 在 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) 原因：找不到类 "com.tencent.common.app.QFixApplicationImpl"，在路径：DexPathList[[zip 文件 "/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/lib/arm64, /data/app/~~oQog1fnyxDwRGR8Vdsb00A==/com.tencent.mobileqq-YLGD9HxNQEcZeOT9G8o-BQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] 在 dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259) 在 java.lang.ClassLoader.loadClass(ClassLoader.java:637) 在 java.lang.ClassLoader.loadClass(ClassLoader.java:573) 在 android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) 在 android.app.Instrumentation.newApplication(Instrumentation.java:1251) 在 android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503) 创建应用内部 ... 11 个更多 — 直接回复这封电子邮件，查看 GitHub 上的内容，或取消订阅。 您收到此消息是因为您是该主题的作者。消息 ***@***.***

我看不到附件？

**Comment by aizaimosaou** [comment]
[log.zip](https://github.com/user-attachments/files/17175290/log.zip) 你好，可能是格式有问题，我转换为zip格式，再重新发送一次
