### ISSUE TITLE
114^5不对啊

### ISSUE THREAD

**Issue by lmf1468** [Nekozuka-Hibiki/QQ-SyRadiant#6]
上次还是对的

**Comment by lmf1468** [comment]
密码又不对，群组讨论也不开，就在这硬猜

**Comment by Nekozuka-Hibiki** [comment]
你好，密码不对不是我的问题。群组讨论不开也不是我的问题，你如果无法获得密钥可以选择不使用，这并不是一个好用的作品

**Comment by lmf1468** [comment]
有没有可能你密码设错了？

**Comment by Fanzhoukanyu** [comment]
幽默老哥



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月19日(周五) 晚上11:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Nekozuka-Hibiki/QQ-SyRadiant] 114^5不对啊 (Issue #6)




 
有没有可能你密码设错了？
